"""Setup wizard for first-time configuration."""

from __future__ import annotations

import os
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

from llm_usage.config import _default_config_dir, get_profile_env_file

console = Console()


def run_setup_wizard(profile: str | None = None) -> None:
    """Interactive setup wizard for first-time configuration."""
    console.print(
        Panel.fit(
            "[bold cyan]llm-usage Setup Wizard[/bold cyan]\n"
            "This wizard will help you configure llm-usage.",
            border_style="cyan",
        )
    )

    config_dir = _default_config_dir()
    env_file = get_profile_env_file(profile) if profile else config_dir / ".env"
    config_dir.mkdir(parents=True, exist_ok=True)

    existing_keys: dict[str, str] = {}
    if env_file.exists():
        console.print(f"[yellow]Found existing config at {env_file}[/yellow]")
        if not Confirm.ask("Update this configuration?", default=True):
            console.print(
                "[dim]Setup cancelled. Your existing configuration is unchanged.[/dim]"
            )
            return
        existing_keys = _parse_existing_env(env_file)

    console.print("\n[bold]Provider Configuration[/bold]")
    console.print("[dim]Leave blank to skip. Only configure what you use.[/dim]\n")

    env_vars: dict[str, str] = dict(existing_keys)

    def maybe_key(label: str, env_name: str) -> None:
        if not Confirm.ask(f"Configure {label}?", default=bool(existing_keys.get(env_name))):
            return
        key = Prompt.ask(
            f"{label} key",
            default=existing_keys.get(env_name, ""),
            password=True,
        )
        if key:
            env_vars[env_name] = key
        elif env_name in env_vars and not key:
            # Empty input with no default: leave existing alone
            pass

    maybe_key("Anthropic Admin (Claude)", "ANTHROPIC_ADMIN_KEY")
    maybe_key("OpenAI Admin", "OPENAI_ADMIN_KEY")
    maybe_key("xAI", "XAI_API_KEY")
    maybe_key("Cursor", "CURSOR_API_KEY")
    maybe_key("Google Gemini", "GEMINI_API_KEY")
    maybe_key("OpenRouter", "OPENROUTER_API_KEY")
    maybe_key("Cohere", "COHERE_API_KEY")
    maybe_key("Mistral AI", "MISTRAL_API_KEY")
    maybe_key("Replicate", "REPLICATE_API_KEY")
    maybe_key("Hugging Face", "HUGGINGFACE_API_KEY")

    console.print("\n[bold]Budget & App[/bold]")
    env_vars["LLM_USAGE_BUDGET_LIMIT"] = Prompt.ask(
        "Monthly budget limit (USD)",
        default=existing_keys.get("LLM_USAGE_BUDGET_LIMIT", "100.0"),
    )
    env_vars["LLM_USAGE_BUDGET_ALERT_THRESHOLD"] = Prompt.ask(
        "Budget alert threshold (0–1)",
        default=existing_keys.get("LLM_USAGE_BUDGET_ALERT_THRESHOLD", "0.9"),
    )
    env_vars["LLM_USAGE_DAYS"] = Prompt.ask(
        "Default lookback days",
        default=existing_keys.get("LLM_USAGE_DAYS", "30"),
    )
    env_vars["LLM_USAGE_PORT"] = Prompt.ask(
        "Dashboard port",
        default=existing_keys.get("LLM_USAGE_PORT", "8765"),
    )

    _write_env_file(env_file, env_vars)
    console.print(
        Panel.fit(
            f"[bold green]Setup complete![/bold green]\n"
            f"Configuration saved to {env_file}\n"
            f"Next: [bold]llm-usage status[/bold] or [bold]llm-usage validate[/bold]",
            border_style="green",
        )
    )


def _parse_existing_env(env_file: Path) -> dict[str, str]:
    env_vars: dict[str, str] = {}
    try:
        for line in env_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            env_vars[key.strip()] = value.strip().strip('"').strip("'")
    except OSError:
        pass
    return env_vars


def _write_env_file(env_file: Path, env_vars: dict[str, str]) -> None:
    # Prefer a stable order for common keys; append the rest sorted.
    preferred = [
        "ANTHROPIC_ADMIN_KEY",
        "OPENAI_ADMIN_KEY",
        "OPENAI_API_KEY",
        "XAI_API_KEY",
        "CURSOR_API_KEY",
        "CURSOR_SESSION_TOKEN",
        "GEMINI_API_KEY",
        "OPENROUTER_API_KEY",
        "COHERE_API_KEY",
        "MISTRAL_API_KEY",
        "REPLICATE_API_KEY",
        "HUGGINGFACE_API_KEY",
        "LLM_USAGE_BUDGET_LIMIT",
        "LLM_USAGE_BUDGET_ALERT_THRESHOLD",
        "LLM_USAGE_DAYS",
        "LLM_USAGE_PORT",
    ]
    lines = ["# llm-usage configuration", "# Generated by setup wizard", ""]
    seen: set[str] = set()
    for key in preferred:
        if key in env_vars and env_vars[key] != "":
            lines.append(f"{key}={env_vars[key]}")
            seen.add(key)
    for key in sorted(env_vars):
        if key not in seen and env_vars[key] != "":
            lines.append(f"{key}={env_vars[key]}")
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(env_file, 0o600)
    except OSError:
        pass
